# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created: Thu Apr 10 15:45:23 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 458)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/toggle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.newAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newAction.setIcon(icon1)
        self.newAction.setObjectName("newAction")
        self.openAction = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon2)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAction.setIcon(icon3)
        self.saveAction.setObjectName("saveAction")
        self.insertAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/add-tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertAction.setIcon(icon4)
        self.insertAction.setObjectName("insertAction")
        self.deleteAction = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/close-tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAction.setIcon(icon5)
        self.deleteAction.setObjectName("deleteAction")
        self.searchAction = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchAction.setIcon(icon6)
        self.searchAction.setObjectName("searchAction")
        self.randomAction = QtWidgets.QAction(MainWindow)
        self.randomAction.setObjectName("randomAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutAction.setIcon(icon7)
        self.aboutAction.setObjectName("aboutAction")
        self.optionAction = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionAction.setIcon(icon8)
        self.optionAction.setObjectName("optionAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon9)
        self.exitAction.setObjectName("exitAction")
        self.toolBar.addAction(self.newAction)
        self.toolBar.addAction(self.openAction)
        self.toolBar.addAction(self.saveAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.searchAction)
        self.toolBar.addAction(self.deleteAction)
        self.toolBar.addAction(self.insertAction)
        self.toolBar.addAction(self.randomAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.optionAction)
        self.toolBar.addAction(self.aboutAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.exitAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SkipList by bss"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.newAction.setText(_translate("MainWindow", "新建"))
        self.newAction.setToolTip(_translate("MainWindow", "新建"))
        self.openAction.setText(_translate("MainWindow", "打开"))
        self.openAction.setToolTip(_translate("MainWindow", "打开"))
        self.saveAction.setText(_translate("MainWindow", "保存"))
        self.saveAction.setToolTip(_translate("MainWindow", "保存"))
        self.insertAction.setText(_translate("MainWindow", "插入(&I)"))
        self.insertAction.setToolTip(_translate("MainWindow", "插入"))
        self.insertAction.setShortcut(_translate("MainWindow", "Alt+I"))
        self.deleteAction.setText(_translate("MainWindow", "删除(&D)"))
        self.deleteAction.setToolTip(_translate("MainWindow", "删除"))
        self.deleteAction.setShortcut(_translate("MainWindow", "Alt+D"))
        self.searchAction.setText(_translate("MainWindow", "搜索(&S)"))
        self.searchAction.setToolTip(_translate("MainWindow", "搜索"))
        self.searchAction.setShortcut(_translate("MainWindow", "Alt+S"))
        self.randomAction.setText(_translate("MainWindow", "随机插入(&R)"))
        self.randomAction.setToolTip(_translate("MainWindow", "随机插入"))
        self.randomAction.setShortcut(_translate("MainWindow", "Alt+R"))
        self.aboutAction.setText(_translate("MainWindow", "关于(&A)"))
        self.aboutAction.setToolTip(_translate("MainWindow", "关于"))
        self.aboutAction.setShortcut(_translate("MainWindow", "Alt+A"))
        self.optionAction.setText(_translate("MainWindow", "选项(&O)"))
        self.optionAction.setToolTip(_translate("MainWindow", "选项"))
        self.optionAction.setShortcut(_translate("MainWindow", "Alt+O"))
        self.exitAction.setText(_translate("MainWindow", "退出(&X)"))
        self.exitAction.setToolTip(_translate("MainWindow", "退出"))
        self.exitAction.setShortcut(_translate("MainWindow", "Alt+X"))

import resource_rc
